type Query {
    #BankAccount est entre crochets car c est un type de retour qui est une liste car il y a pls accounts
    #GET ACCOUNTS
    accountsList: [BankAccount]
    bankAccountById(id: String): BankAccount
    customers : [Customer]
}

#BankAccount est un type donc il faut le déclarer dans le schema
type BankAccount {
    id: String,
    createdAt: Float,
    balance: Float,
    currency: String,
    type : String
    customer: Customer
}

type Mutation {
    addAccount(bankAccount: BankAccountDTO): BankAccount
    updateAccount(id: String, bankAccount: BankAccountDTO): BankAccount
    deleteAccount(id: String): Boolean
}

type Customer {
    id: ID,
    name: String,
    bankAccounts: [BankAccount]
}
input BankAccountDTO {
    balance: Float,
    currency: String,
    type : String
}